#!/usr/bin/env bash

main() {
    curl --silent "$REDMINE_HOST/projects.json?limit=1000" -H "X-Redmine-API-Key":"$REDMINE_API_KEY" | jq '.projects[] | { id: .id, name: .name}'
}

.  redmine-check
check_env
main "$@"
