#!/usr/bin/env bash

main() {
    curl --silent "$REDMINE_HOST/issue_statuses.json?limit=1000" -H "X-Redmine-API-Key":"$REDMINE_API_KEY" | jq '.issue_statuses'
}

.  redmine-check
check_env
main "$@"
