#!/usr/bin/env bash

main() {
    http GET "$REDMINE_HOST/projects.json" limit==1000 "X-Redmine-API-Key":"$REDMINE_API_KEY" | jq '.projects[] | { id: .id, name: .name}'
}

.  redmine-check
check_env
main "$@"
