#!/usr/bin/env bash

set -o nounset

main() {
    if [[ -z $REDMINE_API_KEY ]]
    then
        echo 'Please set $REDMINE_API_KEY variable'
        exit 1
    fi

    if [[ -z $REDMINE_HOST ]]
    then
        echo 'Please set $REDMINE_HOST variable'
        exit 1
    fi

    if (( $# != 5 ))
    then
        echo "Usage: $0 <project_id> <status_id> <next_status_id> <assignee> <build_number>"
        exit 1
    fi

    issues=$(http GET "$REDMINE_HOST/issues.json" project_id==$1 status_id==$2 "X-Redmine-API-Key":"$REDMINE_API_KEY" | jq '.issues | map(.id) | .[]')
    IFS='
    '
    readarray -t lines <<< "$issues"

    for issue_id in "${lines[@]}"
    do
        if [[ $issue_id == "" ]]; then
            continue
        fi
        echo "{ \"issue\": { \"assigned_to_id\": $4, \"status_id\": $3, \"custom_fields\": [{\"id\": 32, \"value\": \"$5\" }] }}" |
            http PUT "$REDMINE_HOST/issues/$issue_id.json" "X-Redmine-API-Key":"$REDMINE_API_KEY" >/dev/null
        echo "Update issue $issue_id"
    done
}

main "$@"
