#!/usr/bin/env bash

if [[ -z $REDMINE_API_KEY ]]
then
    echo 'Please set $REDMINE_API_KEY variable'
    exit 1
fi

if [[ -z $REDMINE_HOST ]]
then
    echo 'Please set $REDMINE_HOST variable'
    exit 1
fi

brew install httpie jq
