#!/usr/bin/env bash

set -o nounset

main() {
    if [[ -z $REDMINE_API_KEY ]]
    then
        echo 'Please set $REDMINE_API_KEY variable'
        exit 1
    fi

    if [[ -z $REDMINE_HOST ]]
    then
        echo 'Please set $REDMINE_HOST variable'
        exit 1
    fi

    if (( $# != 2 ))
    then
        echo "Usage: $0 <issue_id> <hours>"
        exit 1
    fi
    echo "{ \"time_entry\": {\"issue_id\": $1, \"hours\": $2 } }" | http POST "$REDMINE_HOST/time_entries.json" "X-Redmine-API-Key":"$REDMINE_API_KEY" >/dev/null
}

main "$@"
