#!/usr/bin/env bash

main() {
    if (( $# != 2 ))
    then
        echo "Usage: $0 <issue_id> <hours>"
        exit 1
    fi
    echo "{ \"time_entry\": {\"issue_id\": $1, \"hours\": $2 } }" | http POST "$REDMINE_HOST/time_entries.json" "X-Redmine-API-Key":"$REDMINE_API_KEY" >/dev/null
}

.  ./redmine-check
check_env
main "$@"
