#!/usr/bin/env bash

main() {
    project_id=""

    while getopts ":p:" opt; do
        case $opt in
            p ) project_id=$OPTARG ;;
            \? ) print_usage ;;
            :)
            echo "Option -$OPTARG requires an argument."
            exit 1
            ;;
        esac
    done

    [[ -z "$project_id" ]] && print_usage
    http GET "$REDMINE_HOST/issues.json" project_id==$project_id limit==1000 "X-Redmine-API-Key":"$REDMINE_API_KEY" | jq '[.issues[].author] | unique_by(.id)'
}

print_usage() {
    echo "Usage: $0 -p <project_id>"
    exit 1
}

.  ./redmine-check
check_env
main "$@"
